[IMP] partner_credit_limit and payment_term_type: Migrated to v9
Vauxoo/addons-vauxoo pull request #1076
Opened 2016-10-07 05:13 UTC by egrivero

MIgrated to v9 the module partner_credit_limit and payment_term_type

2016-10-07 16:19 UTC, egrivero commented
Hi @moylop260 

What is the error travis showing me here? I do not understand

2016-10-07 16:32 UTC, luistorresm commented
@egrivero 

You need add this dependance cython [here](https://github.com/Vauxoo/addons-vauxoo/blob/9.0/requirements.txt)

Regards

2016-10-07 16:41 UTC, zaoral commented
> @egrivero
> 
> You need add this dependance cython here
> 
> Regards

@luistorresm @egrivero 
FYI I already made the poc and I added the dependency but still not work. You can see this in #1074

2016-10-07 16:42 UTC, zaoral commented
NOTE: The change I made was in 8.0 and do not fix the error. And not sure but for 9.0 I think that the result probably could be the same

2016-10-07 16:44 UTC, luistorresm commented
Thanks @zaoral 

I was added the dependency [here](https://github.com/Vauxoo/imeqmo/pull/5/files#diff-b4ef698db8ca845e5845c4618278f29aR2) and the travis was generated.

But I do not know because here not work.

Regards

2016-10-07 16:49 UTC, egrivero commented
Thanks @zaoral @luistorresm 
I will add it here just to prove that generates results

2016-10-07 17:18 UTC, moylop260 commented
Somebody could help me to apply the following patch https://github.com/OCA/maintainer-quality-tools/pull/355?

2016-10-07 18:13 UTC, egrivero commented
Corrected the error it add the dependence to cython

2016-10-07 18:29 UTC, egrivero commented
Can someone check if any changes you make in this PR are well so it can be merge?

2016-10-10 14:48 UTC, hbto commented
@moylop260 

On the way

> 
Somebody could help me to apply the following patch OCA/maintainer-quality-tools#355?

2016-10-10 16:33 UTC, hbto commented
Problem with Pandas / Cython fixed at Vauxoo/maintainer-quality-tools@a9759c9

Your travis instances shall begin to be build flawlessly.

Best Regards.

2016-10-17 19:44 UTC, egrivero commented
Hi @moylop260, can you help me to merge this PR?

2016-10-17 19:53 UTC, moylop260 requested changes

2016-10-17 19:53 UTC, moylop260 commented on requirements.txt
> +cython >= 0.24.1
Remove cython

2016-10-17 19:54 UTC, moylop260 commented
Could you request approvals before of merging please?

2016-10-17 20:18 UTC, egrivero commented
Eliminate the requirement line of file, but it gives me an error travis.

I will ask for approval so that it can be merge

2016-11-10 17:59 UTC, egrivero commented
@moylop260 

Functional review of the approved changes here Vauxoo/imeqmo#18. Can you please help me with the merge of this PR?

2016-11-10 19:29 UTC, moylop260 approved these changes
LGTM just small questions to know the "Why"

2016-11-10 19:29 UTC, moylop260 commented on partner_credit_limit/model/partner.py
> +                 ('move_id.state', '!=', 'draft'),
`state` field is not present?

2016-11-10 19:29 UTC, moylop260 commented on partner_credit_limit/model/sale.py
> +        self.check_limit()
Why this change is required for the migration of the module?

2016-11-10 19:29 UTC, moylop260 commented on partner_credit_limit/tests/common.py
> +    def _load(self, module, *args):
Is this code copied from:___?

2016-11-10 19:30 UTC, moylop260 commented
Create the pr dummy and request review to leader of the project

2016-11-10 19:37 UTC, egrivero commented on partner_credit_limit/model/partner.py
> +                 ('move_id.state', '!=', 'draft'),
In version 9, I did not get the state field in the model account.move.line

2016-11-10 19:48 UTC, egrivero commented on partner_credit_limit/model/sale.py
> +        self.check_limit()
Before the call to that function was made by the workflow, but in version 9 there is no sales workflow, so pass the validation call to the function that is responsible for confirming the sales order

2016-11-10 19:48 UTC, egrivero commented on partner_credit_limit/model/sale.py
> +        self.check_limit()
Before the call to that function was made by the workflow, but in version 9 there is no sales workflow, so pass the validation call to the function that is responsible for confirming the sales order

2016-11-10 19:51 UTC, egrivero commented
The PR dummy is this Vauxoo/imeqmo#18, it is functionally approved, and I wanted it to be technically reviewed here.

2016-11-10 19:57 UTC, egrivero commented on partner_credit_limit/tests/common.py
> +    def _load(self, module, *args):
This code copied it from [here](https://github.com/odoo/odoo/blob/9.0/addons/account_asset/tests/test_account_asset.py#L10), I needed accounting data demo that in version 9 is no already loaded, but there are the files with the information.

2016-11-10 19:58 UTC, moylop260 commented
Thanks for clarify

2016-11-10 19:59 UTC, merged

2016-11-10 20:09 UTC, egrivero commented
Thanks @moylop260