[REF] payment_term_type: Added a Redme and  compleate help field descriptions
Vauxoo/addons-vauxoo pull request #1105
Opened 2016-11-07 17:10 UTC by hugho-ad

FIX https://github.com/Vauxoo/addons-vauxoo/issues/908#issuecomment-258495111

2016-11-07 21:03 UTC, hugho-ad commented
@zaoral 

Here is the documentation

2016-11-07 23:50 UTC, zaoral requested changes
Hi @hugho-ad 

Thank you for add the modules README.rst.
I leave you some changes before merge.

Best Regards

Please could you

2016-11-07 23:50 UTC, zaoral commented on payment_term_type/README.rst
> +  two ore more exhibitions (partialities) or \n when the payments are covered
remove the \n

2016-11-07 23:50 UTC, zaoral commented on payment_term_type/README.rst
> +In Settings> Account you can find a selection field payment_type that can be
When you say

> In Settings> Account you can find a selection field payment_type 

I think will better to refer the exact path of the menu and mention the human readable name of the field, for example: 

> In the`Settings > Configuration > Accounting` wizard you can find the the **Payment Term Type** (`payment_type)` option

2016-11-07 23:50 UTC, zaoral commented on payment_term_type/README.rst
> +  The payment term will be cash type when the payments have been covered in
> The payment term will be cash type **when the payments have been covered in
 just one exhibition.** without matter the date of payment or **when the payments
 have been covered in just one exhibition**, in the same day that the  sale
 order be confirmed.


This paragraph repeat the same sentence twice in he form this or that, please could you rewrote this paragh

2016-11-07 23:50 UTC, zaoral commented on payment_term_type/README.rst
> +`here <https://github.com/Vauxoo/addons-vauxoo/issues/new?body=module:%20payment_term_type%0Aversion:%201.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20beh
> `here <https://github.com/Vauxoo/addons-vauxoo/issues/new?body=module:%20payment_term_type%0Aversion:%201.0%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**&title=[8.0]%20yoytec_rma_workflow:%20problem%20summary%20here>`_.

You are referring to yoytec_rma_workflow, please update to refer to the current module. 
![image](https://cloud.githubusercontent.com/assets/7593953/20081006/771020b8-a512-11e6-8fe3-d1aa906789b1.png)

2016-11-08 00:27 UTC, hugho-ad commented
@zaoral thanks for your reviewing, Comments Done

2016-11-10 19:32 UTC, hugho-ad commented
@zaoral can you merge if you agree?

2016-11-10 19:35 UTC, zaoral approved these changes
Yes
I will perform the merge
Thank you for the contribution @hugho-ad

2016-11-10 19:36 UTC, zaoral commented
I have not merge permissions xD.

@moylop260 
Please can you help us with this merge?

Best Regards

2016-11-10 20:02 UTC, merged