[IMP] account_voucher_tax, account_move_line_base_tax,
Vauxoo/addons-vauxoo pull request #1128
Opened 2016-11-25 18:22 UTC by luistorresm

account_voucher_tax_sat: Added that consider amount base in lines to
supplier invoice refund.

When was generated an invoice, this is paid and after is generated an
invoice refund, the movement generated by tax in the payment of that
refund must be amount base to report in DIOT report.

Temporary removed validation that not allow generate movements to DIOT
with amount base in negative

Improve some codes and fixed lint errors

2016-12-09 16:09 UTC, luistorresm commented
@JulioSerna 


Could you check this PR please? Is to fix the DIOT to invoice refund.

Regards

2017-04-19 23:05 UTC, JulioSerna commented on account_voucher_tax/account_voucher.py
> +                debit_line_vals.update({
It is not easy to see different between change by pylint and change to resolve the issue, I guess that this is the main change to resolver the issue

LGTM

2017-04-19 23:27 UTC, luistorresm commented on account_voucher_tax/account_voucher.py
> +                debit_line_vals.update({
Yes @JulioSerna

2017-04-19 23:27 UTC, JulioSerna approved these changes

2017-04-24 20:13 UTC, sabrinagnu approved these changes

2017-04-24 20:57 UTC, josemoralesp requested changes

2017-04-24 20:57 UTC, josemoralesp commented on account_move_line_base_tax/account.py
> +            if all([cat_tax, cat_tax.name == 'IVA-RET', line.credit <= 0,
I left you a comment in another PR but with the a similar request that I want to see here:

https://github.com/Vauxoo/odoo-mexico-v2/pull/390#discussion_r113048608

2017-04-24 20:57 UTC, josemoralesp commented on account_voucher_tax/account_voucher.py
> +        if all([line_tax, line_tax.tax_category_id,
The same here:
https://github.com/Vauxoo/odoo-mexico-v2/pull/390#discussion_r113048608

2017-04-24 20:57 UTC, josemoralesp commented on account_voucher_tax/account_statement_bank.py
> +from __future__ import division
This change may modify the result of some methods here. Are there unit tests to verify the results?
We have had problems in other instances when we have added this change.
Let me know if you consider that there is no problem with this change.

2017-04-25 20:50 UTC, luistorresm commented
Done @josemoralesp

2017-04-25 21:14 UTC, josemoralesp approved these changes

2017-04-25 23:44 UTC, merged