[IMP] Some improves to make more fast the methods
Vauxoo/addons-vauxoo pull request #1132
Opened 2016-11-30 03:49 UTC by luistorresm

2016-11-30 03:49 UTC, luistorresm commented
@hbto 

What do you think about this PR?

Regards

2016-11-30 05:18 UTC, hbto commented on aging_due_report/wizard/wizard.py
> +        field_sum2 = ['residual', 'payment', 'total']
field_sum = ['residual', 'payment', 'total']
...
field_names = field_spans + field_sum + ['not_due']

2016-11-30 05:20 UTC, hbto commented on aging_due_report/wizard/wizard.py
> +                for fsum in field_sum2:
keeping same field_sum:
getting rid of conditional statement and
step back the indentation to as it is no longer a statement inside condition.

2016-11-30 05:27 UTC, hbto commented
@luistorresm Thanks for your optimization,
Just a minor changes in form, and all can be merged.

Regards

2016-12-01 01:39 UTC, luistorresm commented
Done @hbto 

Thanks

2016-12-01 02:27 UTC, hbto commented
+1 Can be merged

2016-12-01 02:31 UTC, luistorresm commented
@dsabrinarg 

Could you merge this PR please

2016-12-01 03:14 UTC, moylop260 requested changes

2016-12-01 03:14 UTC, moylop260 commented on aging_due_report/wizard/wizard.py
> +                                 lambda r: r.invoice_id)]
You can use `filtered('invoice_id')`

2016-12-01 03:18 UTC, moylop260 commented on aging_due_report/wizard/wizard.py
> +            for aml_brw in aawd_brw.invoice_id.payment_ids]
Is posible use mapped?

2016-12-01 03:19 UTC, moylop260 commented on aging_due_report/wizard/wizard.py
> +                                         'sale', 'purchase'))]
Is posible use mapped here too?

2016-12-09 16:34 UTC, luistorresm commented on aging_due_report/wizard/wizard.py
> +                                         'sale', 'purchase'))]
@moylop260 

How do you think that the mapped method is used here?

2016-12-09 16:38 UTC, moylop260 commented on aging_due_report/wizard/wizard.py
> +                                         'sale', 'purchase'))]
You are using filtered (good!) but mapped is not used yet.

I mean, you could use:
`aml_lines.filtered(lambda r: r.journal_id.type in ('sale', 'purchase'))].mapped('date')`

2020-06-09 04:12 UTC, luisg123v commented
This seems abandoned, it has no activity from a long time ago, so I'll close it.

Feel free to reopen if if it's not.

2020-06-09 04:12 UTC, closed without merging