[IMP] Optimization of process to get stock_card values
Vauxoo/addons-vauxoo pull request #1181
Opened 2017-02-24 19:26 UTC by josemoralesp

2017-02-24 19:29 UTC, hbto commented
Could create a PR for two outstanding customer instances in order to check that 
we are not breaking anything

2017-02-24 19:34 UTC, hbto approved these changes

2017-02-24 19:53 UTC, hbto requested changes
There are some changes to apply yet, I have seen some actual data that differs, does not match, in two different instances

2017-02-24 20:30 UTC, hbto approved these changes
I have check and the cause of the mismatching values is not in this PR, but in another PR the one in TyP, so, there was changed the code to fix the problem.

Go ahead with merging

2017-02-24 20:31 UTC, hbto commented on stock_card/model/stock_card.py
> +                sm.move_dest_id AS move_dest_id,
Delete This line is written twice

2017-02-26 20:34 UTC, josemoralesp commented
PR: 
TYP: https://github.com/Vauxoo/typ/pull/306
LODI: https://github.com/Vauxoo/lodigroup/pull/658

2017-02-27 05:03 UTC, hbto commented
as both are ok I will endorse this PR
+1

2017-02-28 01:09 UTC, JulioSerna approved these changes

2017-02-28 01:10 UTC, JulioSerna commented
👍

2017-02-28 18:35 UTC, merged