[ADD] stock_card: add translation terms
Vauxoo/addons-vauxoo pull request #1188
Opened 2017-03-22 14:15 UTC by jorgescalona

2017-03-22 17:16 UTC, JulioSerna commented
@hbto 

Could you check this pr?

2017-03-22 18:44 UTC, hbto commented
@jorgescalona @JulioSerna 

Checking

2017-03-22 18:49 UTC, hbto requested changes

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "El producto solicitado no se puede mostrar no tiene movimientos"
El producto solicitado no tiene movimientos que/para mostrar

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
>  msgstr "Obtener Movimiento"
Obtener Movimientos

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Generar Tarjeta de inventario"
Generar Tarjeta de Inventario

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Mensaje para la orden de compra"
Mensaje para la Línea de la Orden de Compra

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Mensaje para la línea de venta"
Mensaje para la Línea de la Orden de Venta

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Orden de compra"
Línea de la Orden de Compra

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Orden de venta"
Línea de la Orden de Venta

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Fecha de vencimiento de tarjeta de inventario"
Fecha de Borde en Tarjeta de Inventario

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Generar Tarjeta de inventario"
Generar Tarjeta de Inventario

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Información de la Tarjeta de inventario"
Información de la Tarjeta de Inventario

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Audifonos VX"
Audífonos VX

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Almacen"
Almacén

2017-03-22 18:49 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Audifonos VX"
Audífonos VX

2017-03-22 19:08 UTC, jorgescalona commented
@hbto check again pls!

2017-03-22 19:38 UTC, hbto approved these changes

2017-03-22 19:44 UTC, JulioSerna commented
@jorgescalona 

The intention of this pr it was translate terms added int PR #1187  but I can not see them, 
e.g this [fields](https://github.com/Vauxoo/addons-vauxoo/pull/1187/files#diff-ccc4b7883a638a1414f96e7be4d11a87R152)

2017-03-22 20:27 UTC, hbto commented
Actually that is the main concern on this issue.

Thanks for highlight it @JulioSerna 

Regards

2017-03-22 20:43 UTC, jorgescalona commented
> @jorgescalona
> 
> The intention of this pr it was translate terms added int PR #1187 but I can not see them,
> e.g this fields

Sure i'll take care of it

2017-03-22 23:04 UTC, jorgescalona commented
> @jorgescalona
> 
> The intention of this pr it was translate terms added int PR #1187 but I can not see them,
> e.g this fields

Fix @JulioSerna .....   Please @hbto you can check the terms please!

2017-03-23 16:35 UTC, hbto requested changes

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Entrada de Asiento Contable"
Asiento Contable de Ajuste

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Precio de Costo en la Etiqueta del Producto"
Etiqueta => Pestaña

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Crear Entrada de Asiento Contable"
Crear Asiento Contable de Ajuste

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Entrada de Diario Contable Creada si se Solicita Valoración de Ajuste"
Asiento Contable Creado si ....

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Logistical Valuation"
Término no traducido

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Cantidad en mano de Etiquetas de Producto"
Etiqueta => Ficha

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Tarjeta de Inventario Costo"
Costo en Tarjeta de Inventario

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Tarjeta de Inventario Fecha"
Fecha en Tarjeta...

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Tarjeta de Inventario Cantidad."
Cantidad en ...

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Valorar Diferecia de Porcentaje."
Diferencia Porcentual de Valoración

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Diferencia de Valuación"
... Valoración

2017-03-23 16:35 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Difrencia de Valuación entre Valuación Contable y Logística"
Diferencia * de Valoración* ... Valoración....

2017-03-23 17:09 UTC, jorgescalona commented
@hbto check again pls!

2017-03-23 17:47 UTC, hbto requested changes
Cambiar todos los textos Valuación por Valoración

2017-03-23 17:47 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Entrada Contable de Ajuste"
Asiento Contable de Ajuste

2017-03-23 17:47 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "El Producto solicitado no se a Movido para Mostrar"
El producto solicitado no tiene Movimientos para mostrar

2017-03-23 17:47 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Etiqueta => Pestaña"
Mi pana, cuando escribí Etiqueta => Pestaña 
es obvio que debías cambiar el texto `Etiqueta por Pestaña`,

2017-03-23 18:12 UTC, hbto commented
@jorgescalona 
> Cambiar todos los textos Valuación por Valoración
Saludos

2017-03-23 18:41 UTC, jorgescalona commented
> @jorgescalona
> 
>     Cambiar todos los textos Valuación por Valoración
>     Saludos

done! @hbto

2017-03-23 19:10 UTC, hbto requested changes

2017-03-23 19:10 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Difrencia de Valoración entre Valoración Contable y Logística"
Diferencia*

2017-03-23 19:10 UTC, hbto commented on stock_card/i18n/es.po
> +msgstr "Difrencia de Valoración entre Valoración Contable y Logística"
Diferencia Porcentual de Valoración entre la Valoración Contable y Logística

2017-03-24 00:01 UTC, hbto approved these changes

2017-03-25 01:03 UTC, JulioSerna approved these changes

2017-03-25 01:04 UTC, merged