[REF] product_customer_code: Migrate module to new api
Vauxoo/addons-vauxoo pull request #1206
Opened 2017-06-19 22:06 UTC by ysantiago

2017-06-19 22:16 UTC, JulioSerna commented
This PR replace this PR https://github.com/Vauxoo/addons-vauxoo/pull/1201

2017-06-19 22:20 UTC, JulioSerna approved these changes
@moylop260 

Could you check this pr?

2017-06-19 22:26 UTC, JulioSerna commented on product_customer_code/models/product.py
> +    def copy(self, default=None):
Add this behavior into field definition

`product_customer_code_ids = fields.One2many(..., copy=False)`

2017-06-19 22:33 UTC, JulioSerna approved these changes

2017-06-19 22:33 UTC, ysantiago commented on product_customer_code/models/product.py
> +    def copy(self, default=None):
This change is in [5c0b939](https://github.com/Vauxoo/addons-vauxoo/pull/1206/commits/5c0b9397756425c1fdb19ec999454787a950e1fb)

2017-06-19 22:38 UTC, moylop260 commented
Could you reference the dummy PR?

2017-06-19 22:58 UTC, moylop260 requested changes

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/__openerp__.py
> +    "license": "LGPL-3",
Is this correct?
I mean, I'm not sure of change a public module from `AGPL` to `LGPL`

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product.py
> +        copy=False, help='Customer Codes')
Don't use the same text of string for help (better let empty help or add a better long help)

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product.py
> +        product_customer_code_obj = self.env['product.customer.code']
This variable don't have sense defined it out of the `if`

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product.py
> +            if prod_code_ids:
Could you check if the mapped().name_get work for empty cases?
I mean, remove the `if prod_code_ids` and force a prod_code_ids without results for the search.

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product.py
> +            if prod_code_ids:
I didn't find sense to use this variable out of the `if partner_id`
I mean, you could use directly:

```python
partner_id = self._context.get('partner_id')
 if partner_id:
    prod_code_ids = product_customer_code_obj.search(...)
    res = prod_code_ids.mapped('product_id').name_get()
```

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +    product_name = fields.Char('Customer Product Name', help="""This customer's
Use just one double-quote to help because the newline could be displayed from gui

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +
license?

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +                                 index=True, help='Partner Reference')
You are using a search with the following domain: `('product_code', '=', name), ('partner_id', '=', partner_id)`
So you don't need this `index=True` you will need a database complex index with product_code, partner_id

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +                               index=True, help="""This customer's product
Same comment about index

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +                                 self._get_user_default_company())
What about use `default=lambda self: self.env['res.company']._company_default_get('product.customer.code')`?

Similar to [event - default company](https://github.com/odoo/odoo/blob/27a47eb3c3d4b79d8fffb6df66f107a993ddf805/addons/event/event.py#L176)

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/views/product_product_view.xml
> +                            </form>
Add company field with properly group and widget

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/models/product.py
> +                # TODO: Search for product customer name
I didn't understand this `TODO`
Could you help to understand it, please?

2017-06-19 22:58 UTC, moylop260 commented on product_customer_code/__init__.py
> +
Add license

2017-06-19 22:58 UTC, moylop260 commented
Could you add tests for this module to check that is working fine?

2017-06-20 13:50 UTC, moylop260 commented on product_customer_code/models/product.py
> +        if not res:
Use return early

if res:
   return res
other code...

2017-06-20 13:52 UTC, moylop260 commented on product_customer_code/models/product.py
> +            prod_code_ids = []
unused variable

2017-06-20 14:08 UTC, ysantiago commented on product_customer_code/models/product.py
> +                # TODO: Search for product customer name
@moylop260 I don't understand this TODO either. I left it there for that.

2017-06-20 14:24 UTC, ysantiago commented on product_customer_code/models/product.py
> +        if not res:
Change in [3600172](https://github.com/Vauxoo/addons-vauxoo/pull/1206/commits/36001728dab8f0e9c9c524a7fd4de0eec1b2f010)

2017-06-20 14:24 UTC, ysantiago commented on product_customer_code/models/product.py
> +            prod_code_ids = []
Done

2017-06-20 14:43 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +    _description = "Add manies Code of Customer's"
s/manies/many/g

2017-06-20 14:44 UTC, moylop260 commented on product_customer_code/models/product_customer_code.py
> +    _description = "Add manies Code of Customer's"
`Customer's Code`

2017-06-20 14:45 UTC, moylop260 commented
TODO:
- [ ] Dummy PR
- [ ] Video
- [ ] Testing
- [ ] Fix typos

2017-06-20 16:40 UTC, ysantiago commented on product_customer_code/models/product_customer_code.py
> +    _description = "Add manies Code of Customer's"
Change in [847c3e6](https://github.com/Vauxoo/addons-vauxoo/pull/1206/commits/847c3e6d317d3389ac56c1db63e4cfc53f7a8742)

2017-06-20 17:02 UTC, ysantiago commented
@moylop260 

- [x] Dummy PR: [https://github.com/Vauxoo/typ/pull/390](https://github.com/Vauxoo/typ/pull/390)
- [x] Video: [video](https://www.youtube.com/watch?v=9jHeEhJTRwo&feature=youtu.be)
- [x] Testing: [60d013d](https://github.com/Vauxoo/addons-vauxoo/pull/1206/commits/60d013d2eaa993c1d35772092894be027a940bd8)
- [x] Fix typos: [847c3e6](https://github.com/Vauxoo/addons-vauxoo/pull/1206/commits/847c3e6d317d3389ac56c1db63e4cfc53f7a8742)

2017-06-20 17:04 UTC, moylop260 commented on product_customer_code/tests/test_product_customer_code.py
> +        self .assertTrue(self.product.product_customer_code_ids)
Something is wrong with the DUMMY PR because this `self{space}.` don't show a error

2017-06-20 18:12 UTC, ysantiago commented on product_customer_code/tests/test_product_customer_code.py
> +        self .assertTrue(self.product.product_customer_code_ids)
Solved it, can you review again.

2017-06-21 20:57 UTC, merged