[IMP] invoice_discount: Migrating to 11.0
Vauxoo/addons-vauxoo pull request #1268
Opened 2018-04-02 16:50 UTC by ebirbe

Migrating module to Odoo v11.0

* Using new API on models.
* Removing deprecated sale_config_settigs configuration.
* Using standard file and folder names.
* Removing dependency to `sale.group_discount_per_so_line`, now using `base.group_no_one` as Odoo does for `discount` field in views.

2018-04-02 17:07 UTC, ebirbe commented
Hello @moylop260 I need this module active in v11 to complete the task described on https://git.vauxoo.com/vauxoo/lasec/issues/1

Could you review, please?

/cc @rdmachadog

2018-04-02 17:15 UTC, moylop260 requested changes

2018-04-02 17:15 UTC, moylop260 commented on invoice_discount/__manifest__.py
> +        "views/invoice_view.xml",
bumpversion to 11.0...

2018-04-02 17:15 UTC, moylop260 commented on invoice_discount/models/__init__.py
>  #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
Use small comments from template and remove utf-8 for py3 is not required

2018-04-02 17:15 UTC, moylop260 commented on invoice_discount/views/invoice_view.xml
> +
remove extra spaces
Use 4 spaces for each child

2018-04-03 15:14 UTC, ebirbe commented
@moylop260 Review corrections done at last commit. Could you review again and merge if possible, please?

2018-04-04 14:06 UTC, ebirbe commented
Hello @moylop260 is something blocking this merge?

2018-04-04 14:11 UTC, merged