[MIG] Migration of account_asset_move_check 8.0 --> 11.0
Vauxoo/addons-vauxoo pull request #1280
Opened 2018-06-16 00:27 UTC by umiphos

2018-06-18 14:35 UTC, luistorresm commented on account_asset_move_check/__manifest__.py
> +    "auto_install": True,
Are you sure that must be `auto_install=True`?

2018-06-18 14:36 UTC, luistorresm commented on account_asset_move_check/model/account_asset.py
>              res[line.id] = bool(line.move_id or line.historical)
Now in the compute must be assigned the value with self.field, not with dict.

2018-06-18 21:56 UTC, umiphos commented
@dsabrinarg can you please test if this PR do what it's expected of it? thanks in advance

2018-06-20 18:20 UTC, dsabrinarg commented
@umiphos please link the dummy to [this](https://git.vauxoo.com/vauxoo/lodi) repo here

2018-06-20 21:24 UTC, umiphos commented
@dsabrinarg this is the dummy for this migration https://git.vauxoo.com/vauxoo/lodi/merge_requests/17

2018-07-04 02:54 UTC, dsabrinarg commented
@umiphos please solve the conflicts, weird thing, I tested again this today and the last point was working, I will merge and after that if on the test customer environment this fails I will check and assign the fix.

2018-07-04 18:50 UTC, dsabrinarg commented
@josemoralesp functional review 👍

2018-07-04 19:28 UTC, josemoralesp requested changes

2018-07-04 19:28 UTC, josemoralesp commented on account_asset_move_check/model/account_asset.py
> +                    ('move_check', '=', True)])
@umiphos This field isn't stored in the database. Are you sure this is working as expected?

2018-07-04 19:28 UTC, josemoralesp commented on account_asset_move_check/model/account_asset.py
> +        return super(AccountAssetDepreciationLine, self)._get_move_check()
Why are you calling _get_move_check instead of _compute_get_move_check?

2018-07-04 19:28 UTC, josemoralesp commented on account_asset_move_check/model/account_asset.py
> +                                compute="_compute_get_move_check",
The old one had the store=True attribute

2018-07-05 23:43 UTC, dsabrinarg commented
@umiphos may you please check the comments from Jose and fix asap in order to be able of finish this task?.

2018-07-06 21:00 UTC, umiphos commented on account_asset_move_check/model/account_asset.py
> +        return super(AccountAssetDepreciationLine, self)._get_move_check()
fixed, I was trying to stop a lint from happening, but the best practice in this case was to keep the name of the original method, so that I did

2018-07-06 21:48 UTC, umiphos commented on account_asset_move_check/model/account_asset.py
> +                    ('move_check', '=', True)])
It's now stored, and it's working as expected

2018-07-06 21:48 UTC, umiphos commented on account_asset_move_check/model/account_asset.py
> +                                compute="_compute_get_move_check",
done, I omitted that.. thanks

2018-07-06 21:50 UTC, dsabrinarg commented
This is ready for review @umiphos @josemoralesp ?

2018-07-06 21:52 UTC, umiphos commented
yes @dsabrinarg  I updated the dummy for tests https://git.vauxoo.com/vauxoo/lodi/merge_requests/17

@josemoralesp do you agree with the changes?

2018-07-09 23:08 UTC, umiphos commented
@josemoralesp as talked via in person, I added an automated action, it's working as I expected, can you please validate if that that's what you asked?

2018-07-09 23:15 UTC, dsabrinarg commented
Nice, the current behaviour due to the automated action is very nice @umiphos @josemoralesp 👍

2018-07-10 14:22 UTC, merged