[FIX] partner_credit_limit: Add = to the validation condition
Vauxoo/addons-vauxoo pull request #1406
Opened 2020-04-03 20:24 UTC by edy1192

There is data demo with the value of the grace_payment_days field set to
999999, that value must be included.

Improve message that is displayed to the user when the constraint is
executed, to show the value that is trying to save.

![Screenshot from 2020-04-03 14-23-36](https://user-images.githubusercontent.com/11479473/78401822-c6eadd80-75b6-11ea-8de3-546fbf50295e.png)

2020-04-03 20:28 UTC, edy1192 commented
Hi @moylop260 @luisg123v Could you check this please?

In the previous PR, I forgot to put the = to the validation that moy asked me in the [comment](https://github.com/Vauxoo/addons-vauxoo/pull/1405#issuecomment-607581949).

This caused a typ MR to be turning red in the tests because the demo data has 999999 set in the field.

But 999999 is a valid value.

Moy I have no issue / task for this PR, this was commented to me by @JulioSerna 

Julio do you have a task for this?

Regards.

2020-04-03 20:35 UTC, luisg123v requested changes

2020-04-03 20:35 UTC, luisg123v commented on partner_credit_limit/model/partner.py
> +            if not 0 < record.grace_payment_days <= 999999:
`<=` should also be applied for 0.

2020-04-03 20:35 UTC, luisg123v commented on partner_credit_limit/model/partner.py
> +                    _('Invalid value %s: Payment grace days must be between 0 '
`Invalid value %s for Payment grace days: value must...`

2020-04-03 20:35 UTC, luisg123v commented on partner_credit_limit/i18n/es.po
> +msgstr "Valor no válido: %s: Los días de gracia de pago deben estar entre 0 y 999999"
No válido?

I'd use incorrecto or in fault, inválido

2020-04-03 22:13 UTC, luisg123v approved these changes
:+1: 

CC @moylop260

2020-04-03 22:36 UTC, merged

2020-04-04 02:44 UTC, luisg123v commented
@edy1192 could you perform the cherry-pick of these fixes to v12, please?

2020-08-01 04:39 UTC, luisg123v commented
@edy1192,

Could you forward-port this fix to v12, please?