[IMP] product_pricelist_report_qweb: Migrating to v11.0 - T#29976
Vauxoo/addons-vauxoo pull request #1419
Opened 2020-06-09 21:31 UTC by ebirbe

Migrating module from Odoo 8.0 to 11.0

![Selección_999(029)](https://user-images.githubusercontent.com/442938/84202938-8a37d880-aa76-11ea-84a2-53b6444cee57.png)

Module `controller_report_xls` is not migrated to 11.0 so this migration only take care of the PDF format version. So, the report format switch was removed from the UI.

Tests were disabled as they are intended only to check the XLS file generation.

There are two fields in the wizard that seems to have no effect in the resulting report (not because of the migrations, it seems to be happening since the original version):

* Only products in pricelist (`only_prod_pricelist`)
* Only products with price (`products_with_price`)

I didn't change the behavior of these two fields until get further information about how they should behave.

/cc @hugho-ad @dsabrinarg

2020-06-09 21:50 UTC, ebirbe commented
Dummy PR:

https://git.vauxoo.com/vauxoo/lodigroup/-/merge_requests/1045

2020-06-09 22:28 UTC, luisg123v requested changes

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/__manifest__.py
> +    "version": "11.0.0.1.0",
`11.0.1.0.0`

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/__manifest__.py
> +        "wizard/product_pricelist_views.xml",
wizards

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/__manifest__.py
> +        "report/product_pricelist_templates.xml",
reports

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/report/product_pricelist.py
> +# coding: utf-8
Please Remove encoding and license

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
>  #    You should have received a copy of the GNU Affero General Public License
Please remove encoding header and license

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/report/product_pricelist.py
> +from __future__ import division
This is python3, there's no need for `__future__`

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/report/product_pricelist_templates.xml
> +        <template id="report_pricelist" inherit_id="product.report_pricelist">
Wrong indentation, it should be four spaces

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/tests/test_report_product.py
> +    # def test_report_xls_product_pricelist(self):
Remove commented code

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/tests/test_report_product.py
> +    # def _generate_report_product(self):
Remove commented code

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
>  ###############################################################################
Remove encoding header an license

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
>      _inherit = 'product.price_list'
Could you use something less generic, please? ANd without `_` in model name

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
> +    report_format = fields.Selection([
`required=True`

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
> +        if not self.env.user.company_id.logo:
```
company = self.env.user.company_id
if not company.***:
```

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist_views.xml
>          <!--   Product Price List -->
Indentation

2020-06-09 22:28 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist_views.xml
> +                    <!-- Module `controllers_report_xls` not migrated -->
Use word "TODO" to be easily identifiable

2020-06-09 22:34 UTC, luisg123v commented on product_pricelist_report_qweb/report/product_pricelist_templates.xml
> +        <template id="report_pricelist" inherit_id="product.report_pricelist">
Wrong indentation, it should be four spaces

2020-06-15 18:56 UTC, dsabrinarg commented
Functionally 👍 @hugho-ad 
@ebirbe please fix the commented by @luisg123v and let me know to check again.

2020-06-15 23:22 UTC, luisg123v requested changes
Translations need also to be migrated. Could you perform the following, please?
- Re-generate translations and save the result on `es.po`
- Remove file `es_MX.po`

2020-07-18 18:26 UTC, luisg123v commented
Hi @ebirbe,

Is there any news about this?

2020-08-03 13:53 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
>      _inherit = 'product.price_list'
Comment not applicable, because the model `product.price_list` is native from Odoo, it's just being inherited, so resolving.

2020-08-03 13:54 UTC, luisg123v commented on product_pricelist_report_qweb/wizard/product_pricelist.py
> +    report_format = fields.Selection([
This is a model from Odoo, so adding new required fields could cause issues, hence resolving.

2020-08-03 13:59 UTC, luisg123v approved these changes
Given that:
- This has been functionally approved by @dsabrinarg 
- I technically approve this (I just applied small commented suggestiongs: indentation, removing Python headers, bumping to correct version number, etc)
- This is not installed yet in any customer, so it's safe enough
- I'ts been without answer for a long time

I proceed to merge.

CC @moylop260

2020-08-03 14:00 UTC, merged