[ADD] account_chatter: Allows to record changes in CoA, journals and …
Vauxoo/addons-vauxoo pull request #1459
Opened 2020-10-13 18:48 UTC by randall-vx

…account moves.

CoA:

![image](https://user-images.githubusercontent.com/16024775/95902633-4de0f580-0d52-11eb-8266-abb1e5517aec.png)

AM:

![image](https://user-images.githubusercontent.com/16024775/95902540-30139080-0d52-11eb-90bf-279a7b8c4a93.png)

Journal:

![image](https://user-images.githubusercontent.com/16024775/95902579-3dc91600-0d52-11eb-936c-310aa0cfb859.png)

2020-10-13 23:46 UTC, luisg123v requested changes

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
It should be LGPL. This must be fixed in all headers. I'd recommend just removing headers, as the manifest already says LGPL.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_move.py
> +    _translate = False
Why this?

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_account.py
> +    def _message_track(self, tracked_fields, initial):
A docstring would be very welcomed, otherwise one needs to read the whole method to figure out this adds support to track many2many fields.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_account.py
> +                initial_value = ", ".join(initial_value.mapped('name')
- Prefer `display_name` as it's more generic and complete.
- Fix line break

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_account.py
> +                new_value = ", ".join(new_value.mapped('name')
Same here

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_account.py
> +                                    ].create_tracking_values(
Splitting this way is ugly (at least IMHO) and not required

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_journal.py
> +    _translate = False
Same here, I don't think this is required

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_account.py
> +    _translate = False
And here

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/models/account_move.py
> +    _name = "account.move"
Uhhhh this is so controversial man.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/security/security.xml
> +<odoo>
Missing noupdate

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/views/account_account.xml
> +<odoo>
Missing XML header.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/views/account_journal.xml
> +<odoo>
Missing XML header.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/views/account_move.xml
> +<odoo>
Missing XML header

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/__manifest__.py
> +
This line may be removed

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/__manifest__.py
> +        "security/security.xml",
`security/account_chatter_security.xml`

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/__manifest__.py
> +        "views/account_account.xml",
Please add suffix `_views` to all views, this to conform guidelines.

```suggestion
        "views/account_account_views.xml",
```

BTW, I like that files already refers to the full model name.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
LGPL

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/README.rst
> +2. Check > Show account notifications
Reading this, it looks (at least to me) that this is a global setting. To be more descriptive, I'd add an intermediate step mentioning that an user needs to be selected.

Or maybe clarifying that this a user-configurable feature.

2020-10-13 23:46 UTC, luisg123v commented on account_chatter/README.rst
> +1. Settings > Users > Account & Finance
Users & companies

2020-10-13 23:57 UTC, luisg123v requested changes
The screensots provided on the description would fit perfectly also on the README.

2020-10-23 19:16 UTC, randall-vx commented
@luisg123v could you review this PR please ?

Regatas,

2020-10-23 19:39 UTC, luisg123v requested changes
There are comments not applied yet.

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/models/account_account.py
> +    """
Docstrings go inside methods, just after declaration, e.g.

```
def my_awesome_method(self):
    """An explanation of what the method does"""
```

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/models/account_account.py
> +        Track changes in tag_ids and tax_ids fields.
This is done manually because fields tracking is not natively supported for many2many fields

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/README.rst
> +Known issues / Roadmap
This section may be removed

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/models/account_account.py
> +    _translate = False
Please remove all `_translate` attributes.

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/__manifest__.py
> +
This is not applied yet.

2020-10-23 19:39 UTC, luisg123v commented on account_chatter/models/account_account.py
> +                initial_value = ", ".join(initial_value.mapped('name')
Still using `name`

2020-10-23 19:43 UTC, luisg123v commented
Comment https://github.com/Vauxoo/addons-vauxoo/pull/1459#pullrequestreview-507906734 is pending and IMHO easy to apply, just copy images into `static/src/description`

2020-10-24 00:43 UTC, randall-vx commented
> Comment [#1459 (review)](https://github.com/Vauxoo/addons-vauxoo/pull/1459#pullrequestreview-507906734) is pending and IMHO easy to apply, just copy images into `static/src/description`

Done ! Please check !

2020-10-24 02:39 UTC, luisg123v commented
Hi @randall-vx,

Sorry if I wasn't clear enough. I noticed you copied screenshots on the  suggested directory. However, that is not enough for those images to be shown in the module's description. You have to reference them in the README, for instance:

https://github.com/Vauxoo/addons-vauxoo/blame/bdeb3fa257fbcb85a04ef56b3665447f4f7ae845/internal_transfer_with_agreed_amount/README.rst#L10

2020-10-24 18:05 UTC, randall-vx commented
> Hi @randall-vx,
> 
> Sorry if I wasn't clear enough. I noticed you copied screenshots on the suggested directory. However, that is not enough for those images to be shown in the module's description. You have to reference them in the README, for instance:
> 
> https://github.com/Vauxoo/addons-vauxoo/blame/bdeb3fa257fbcb85a04ef56b3665447f4f7ae845/internal_transfer_with_agreed_amount/README.rst#L10

Your example doesn't work...

![image](https://user-images.githubusercontent.com/16024775/97088234-bd75a100-15ec-11eb-8daf-6b9a71bae9f3.png)

PR it's ready to merge now.

2020-10-24 18:32 UTC, luisg123v commented
Hi @randall-vx,

I understand. I will fix it later post-merge.

2020-10-24 18:32 UTC, luisg123v approved these changes

2020-10-24 18:33 UTC, merged

2020-10-24 18:46 UTC, luisg123v commented
@randall-vx next time, remember to squash your commits.