[ADD] stock_by_warehouse_mrp_bom: New stock_by_warehouse module added for mrp.bom.line model
Vauxoo/addons-vauxoo pull request #1517
Opened 2022-01-13 00:01 UTC by agarzaarvizu

2022-01-13 00:43 UTC, agarzaarvizu commented
![Screenshot from 2022-01-12 18-43-03](https://user-images.githubusercontent.com/96079875/149245640-d98661fe-22e3-4f32-8162-aa0997a976bf.png)

2022-01-14 15:48 UTC, goliveirab commented on stock_by_warehouse_mrp_bom/models/mrp_bom.py
> +        __import__('pdb').set_trace()
Remove pdb

2022-01-14 16:17 UTC, CarmenMiranda requested changes
Just a few comments about the readme file, other than that LGTM 👍🏼

2022-01-14 16:17 UTC, CarmenMiranda commented on stock_by_warehouse_mrp_bom/README.rst
> +.. image:: http://screenshots.vauxoo.com/nhomar/stock_by_warehouse_sale_1.png
Hi, It should be great to have the new screenshots here you can use as an example the ones added in the [`stock_by_warehouse_stock`](https://github.com/Vauxoo/addons-vauxoo/blob/12.0/stock_by_warehouse_stock/README.rst),  adding the SS that you put [in the MR comment](https://github.com/Vauxoo/addons-vauxoo/pull/1517#issuecomment-1011591319)

2022-01-14 16:17 UTC, CarmenMiranda commented on stock_by_warehouse_mrp_bom/README.rst
> +Developers usage:
We can delete this section, because this usage is for the `stock_by_warehouse` module

2022-01-17 15:24 UTC, CarmenMiranda commented on stock_by_warehouse_mrp_bom/README.rst
> +Developers usage:
This section still needs to be deleted 🙈

2022-01-17 16:22 UTC, CarmenMiranda approved these changes
@hugho-ad LGTM 👍🏼

2022-01-17 17:19 UTC, hugho-ad commented
@agarzaarvizu 

pls squash your commits into only one

2022-01-17 17:21 UTC, hugho-ad commented
ps update icon image

2022-01-17 18:40 UTC, agarzaarvizu commented
@hugho-ad commits squashed and image updated, please review.

2022-01-17 18:53 UTC, luisg123v requested changes

2022-01-17 18:53 UTC, luisg123v commented on stock_by_warehouse_mrp_bom/README.rst
> +Provide a nice widget in the product on the mrp_bom line to see the quantity of product
```suggestion
Provide a nice widget in the product on the bill of material's line to see the quantity of product
```

2022-01-17 18:53 UTC, luisg123v commented on stock_by_warehouse_mrp_bom/README.rst
> +This module rely on variants and multiple warehouse management
```suggestion
This module relies on variants and multiple warehouse management
```

2022-01-17 18:53 UTC, luisg123v commented on stock_by_warehouse_mrp_bom/__manifest__.py
> +    "name": "Stock by Warehouse on MRP_BOM",
```suggestion
    "name": "Stock by Warehouse on MRP BoM",
```

2022-01-17 18:53 UTC, luisg123v commented on stock_by_warehouse_mrp_bom/__manifest__.py
> +    from the mrp_bom line form.
```suggestion
    from the mrp bill of material's line form.
```

2022-01-17 19:27 UTC, agarzaarvizu commented
@hugho-ad @luisg123v Changes done, please review.

2022-01-17 19:32 UTC, luisg123v approved these changes

2022-01-17 19:35 UTC, luisg123v requested changes
Hi @agarzaarvizu,

Please reword commit to conform guidelines.

Someting like:

```
[ADD] module_name: Module to ...
# blank line between title and description
Module summary
```

2022-01-17 19:43 UTC, agarzaarvizu commented
@luisg123v done

2022-01-17 19:55 UTC, luisg123v commented
@agarzaarvizu not done yet:

- You still have a list instead of a title&description
- Module name is misspelled, it's mrp instead of mpr

2022-01-17 21:09 UTC, agarzaarvizu commented
@luisg123v can you check it now? Please

2022-01-17 22:50 UTC, luisg123v commented
@agarzaarvizu it still does not comply:
- It's still a list (excepting the 1st element)
- There's no space between title and description
- The description is not actually a description. You could paste module's summary instead

2022-01-17 23:09 UTC, agarzaarvizu commented
@luisg123v Done

2022-01-17 23:22 UTC, luisg123v approved these changes

2022-01-17 23:22 UTC, merged