[REF] account_chatter: Show account.account chatter only for specific group
Vauxoo/addons-vauxoo pull request #1546
Opened 2022-05-19 23:23 UTC by edy1192

-  Show account.account chatter only for the group `group_show_account_chatter_notifications`.

2022-05-19 23:24 UTC, edy1192 commented
Hi @luisg123v could you check this please?

Regards.

2022-05-19 23:30 UTC, luisg123v requested changes

2022-05-19 23:30 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +        <field eval="100" name="priority"/>
name goes first

2022-05-19 23:30 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +    <record id="view_account_form_inherit_hidden" model="ir.ui.view">
same ID as inherited view, the view with the group should be the one with a different ID

2022-05-19 23:30 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +        <field name="name">account.account.form.inherit.hidden</field>
```suggestion
        <field name="name">account.account.form.inherit.account.chatter</field>
```

2022-05-19 23:41 UTC, edy1192 commented
Done @luisg123v

2022-05-19 23:55 UTC, luisg123v requested changes

2022-05-19 23:55 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +        <field eval="99" name="priority"/>
You missed this one

2022-05-20 00:00 UTC, luisg123v approved these changes

2022-05-20 00:00 UTC, merged