[FIX] search_action_domain: Make installable with base_automation T#59176
Vauxoo/addons-vauxoo pull request #1554
Opened 2022-07-21 23:02 UTC by rolandojduartem

At the moment to install search_action_domain with base_automation appears
 an error. Error indicates 'create_as_ir_filter is not a valid action on
base.automation'. This fix avoid the validation for the buttons if
base automation is in process.

2022-07-21 23:06 UTC, rolandojduartem commented
Hi, @luisg123v, could you check this fix, I tested it and this module installed correctly.

2022-07-22 00:00 UTC, luisg123v requested changes

2022-07-22 00:00 UTC, luisg123v commented on search_action_domain/models/ir_ui_view.py
> +        if name_manager.model._name == "base.automation":
Add more conditions to affect only the desired button.

Current.

This condition is OK to be the 1st one, because this will discard faster all validations of all other models

2022-07-22 00:07 UTC, luisg123v requested changes
- Please also add a small docstring to explaing that's to don't fail when the base automation module is installed.
- We're hiding the error, but we need also to hide the button when we're on an automated action. That could be achieved by making invisible when `usage = base_automation`

2022-07-22 01:19 UTC, rolandojduartem commented
@luisg123v changes are ready

2022-07-22 22:40 UTC, luisg123v approved these changes

2022-07-22 22:41 UTC, merged