[MIG] product_cost_usd: module migrated to v15.0 t#53826
Vauxoo/addons-vauxoo pull request #1556
Opened 2022-08-11 00:58 UTC by agarzaarvizu

## This PR refers to the task[#53826](https://www.vauxoo.com/web#action=1928&cids=1&id=53862&menu_id=1490&model=project.task&view_type=form)

- product_cost_usd module migrated.

2022-08-11 01:38 UTC, agarzaarvizu commented
@luisg123v Done, please review

cc @desdelinux

2022-08-11 02:42 UTC, luisg123v requested changes
There's only one commit, you should bring the whole history. Follow instructions depicted [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch)

2022-08-11 03:46 UTC, agarzaarvizu commented
@luisg123v Done

2022-08-12 23:01 UTC, luisg123v requested changes

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/models/pricelist.py
> +        date = fields.Date.today()
`context_today`?

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/models/pricelist.py
> +        ondelete={'standard_price_usd': 'set default', 'Cost in USD': 'set default'})
No such option "Cost in USD", there's only one

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/models/sale_order.py
> +        date = self.order_id.date_order
`for line in self:`

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/models/sale_order.py
> +        super()._compute_margin()
I know returning value from a compute method is not important, but it's harmless and don't doing it triggers a lint

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/models/sale_order.py
> +        return
Superfluous return, you're not returning anything, which is the default value when no return is used

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +        self.product.seller_ids = None
`False` or `commands.clear()`

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +    def test_03(self):
test method names should be meaningful

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +    def test_sale_margin_normal(self):
`test_0*`

2022-08-12 23:01 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> -    def test_sale_margin(self):
Why are you removing this test?

2022-08-18 00:34 UTC, agarzaarvizu commented
@luisg123v Done

2022-08-19 04:27 UTC, luisg123v requested changes

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +import pdb
Remove

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +            line.purchase_price = frm_cur._convert(purchase_price, to_cur, self.env.company, date, round=False)
Company from SO, not from env

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +            suitable_rule = line.order_id.pricelist_id.item_ids.filtered(lambda x: x.id == rule)
Since pricelist and SO is used in several places, it would be convenient to save then in variables

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +            return res
This is inside a loop, but you're returning, so only the first record is being considered

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +            frm_cur = self.env.ref("base.USD")
`currency_usd`

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +        """Test the sale margin module using a pricelist with cost in usd."""
```suggestion
        """Test the sale margin module using a pricelist with cost in USD."""
```

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +                "order_line": [
Use the `Form` class, please.

Same below

2022-08-19 04:27 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +        expected_price = float_round(product.standard_price_usd * 1.15, precision_rounding=self.usd.rounding)
Now the currency has a `currency.round(amount)` method

2022-08-19 04:30 UTC, luisg123v commented
@agarzaarvizu task ID is wrong in both title and description

2022-08-19 23:41 UTC, rolandojduartem commented
Hi, @luisg123v and @agarzaarvizu, I have bad news :(. I added this module in tanner_common and I had [these](https://gist.github.com/rolandojduartem/3ecb74bd35bead24d3650e6466008df9) tracebacks using it, indeed, you may see that if I do not add this module the tests are working well [here](https://git.vauxoo.com/vauxoo/tanner-common/-/merge_requests/18)

2022-08-23 05:18 UTC, agarzaarvizu commented
@luisg123v Finally done!! Hahaha please review.

cc @rolandojduartem

2022-08-25 04:03 UTC, luisg123v requested changes
I think some of these can be applied directly in v11

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +            pricelist_id = line.order_id.pricelist_id
```suggestion
            pricelist = line.order_id.pricelist_id
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/sale_order_line.py
> +                return res
I think you meant `continue`

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +        """Test USD pricelist based on cost in usd."""
```suggestion
        """Test USD pricelist based on cost in USD."""
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/tests/test_standard_price_usd.py
> +        self.pricelist_15_usd = self.env["product.pricelist"].create(
I'd recommend moving this to data demo, otherwise this will be created on every test

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/i18n/es.po
> +"Project-Id-Version: Odoo Server 10.0+e\n"
```suggestion
"Project-Id-Version: Odoo Server 15.0+e\n"
```

I'd recomment re-exporting translations

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_pricelist.py
> +        This method always compute the product price, from product currency
```suggestion
        This method always computes the product price, from product currency
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_pricelist.py
> +        conversion is made from USD currency. By this reason we must go back
```suggestion
        conversion is made from USD currency. For this reason, we must go back
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +        list_price = usd_seller.price if usd_seller else 0.0
If seller is not found, it will be an empty recordset, and `empty.float_field` isalready 0.0:

```suggestion
        list_price = usd_seller.price
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +                _("You must have at least one supplier with price in USD" " before assign a Cost in USD")
```suggestion
                _("You must have at least one supplier with price in USD before assigning a Cost in USD")
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +                % (list_price, standard_price_usd)
Use new translation syntax

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +        usd_seller = self.seller_ids.filtered(lambda x: x.currency_id == usd_currency)
Take into account constraints can get a recordset, so I think you should iterate over the result of self to perform validations

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/views/product_template_views.xml
> +<?xml version="1.0" encoding="utf-8"?>
It seems prettier wasn't run for this module

```suggestion
<?xml version="1.0" encoding="utf-8" ?>
```

Same in below cases

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/views/product_template_views.xml
> +
Remove blank line

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/i18n/es.po
> +msgstr "Costo en Dólares"
```suggestion
msgstr "Costo en USD"
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/i18n/es.po
> +msgstr "No puede crear o modificar un producto si el costo en USD es menor que el precio del proveedores..\n"
```suggestion
msgstr "No puede crear o modificar un producto si el costo en USD es menor que el precio del proveedor.\n"
```

2022-08-25 04:03 UTC, luisg123v commented on product_cost_usd/i18n/es.po
> +msgstr "Debe tener al menos un proveedor con precio en Dólares antes de asignar un Costo en Dólares a el producto"
```suggestion
msgstr "Debe tener al menos un proveedor con precio en Dólares antes de asignar un Costo en Dólares al producto"
```

2022-08-26 18:10 UTC, agarzaarvizu commented
@luisg123v Done, please review

2022-08-27 01:12 UTC, luisg123v requested changes

2022-08-27 01:12 UTC, luisg123v commented on product_cost_usd/migrations/11.0.1.0.2/pre-migration.py
> +def delete_inherited_views(cr):
One of the migration tasks is to remove migration scripts

2022-08-27 01:12 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +            prec = product.env["decimal.precision"].precision_get("Product Price")
Decimal precision doesn't depennd on the product

2022-08-27 01:12 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +                        list_price, standard_price_usd
This semmseems to not be the black format:

```suggestion
                        list_price,
                        standard_price_usd,
```

2022-08-27 01:12 UTC, luisg123v commented on product_cost_usd/i18n/es.po
> +msgstr "Línea de la orden de venta"
pedido

2022-08-29 18:58 UTC, agarzaarvizu commented
@luisg123v Done

2022-08-31 17:49 UTC, rolandojduartem commented
Hi, @agarzaarvizu, I just want to say I'm getting this traceback, I just running the check_cost_and_price method.

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/models.py", line 5199, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/build/vauxoo/tanner-common/tanner_common/tests/test_product_template.py", line 35, in test_02_check_cost_and_price                                                        
    self.product.product_tmpl_id.check_cost_and_price()
  File "/home/odoo/build/vauxoo/tanner-common/tanner_common/models/product_template.py", line 24, in check_cost_and_price                                                                    
    return super().check_cost_and_price()
  File "/home/odoo/addons-vauxoo/product_cost_usd/models/product_template.py", line 26, in check_cost_and_price                                                                              
    list_price = usd_seller.price
  File "/.repo_requirements/odoo/odoo/fields.py", line 1050, in __get__
    record.ensure_one()
  File "/.repo_requirements/odoo/odoo/models.py", line 5202, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: product.supplierinfo(3, 1, 2)

cc @luisg123v

2022-08-31 18:07 UTC, luisg123v commented
I've rebased this branch so tests may run

2022-08-31 18:21 UTC, luisg123v requested changes

2022-08-31 18:21 UTC, luisg123v commented on product_cost_usd/models/product_template.py
> +            usd_seller = product.seller_ids.filtered(lambda x: x.currency_id == usd_currency)
```suggestion
            usd_seller = product.seller_ids.filtered(lambda x: x.currency_id == usd_currency)[:1]
```

But maybe `_select_seller` may be used.

2022-08-31 20:59 UTC, agarzaarvizu commented
@luisg123v Done

2022-09-02 19:55 UTC, desdelinux commented
@agarzaarvizu @luisg123v No aparece el tag del campo en la vista del Producto, sólo aparece el valor:

![image](https://user-images.githubusercontent.com/50924836/188227037-3dbf4e0f-cdfc-4b1d-bb02-57f41c3e234d.png)

2022-09-05 22:39 UTC, agarzaarvizu commented
@luisg123v @desdelinux Done

2022-09-06 13:22 UTC, desdelinux commented
LGTM

2022-09-06 13:22 UTC, desdelinux approved these changes

2022-09-06 15:40 UTC, luisg123v approved these changes

2022-09-06 15:41 UTC, merged