[ADD] product_cost_usd: add pre-migration file t#53862
Vauxoo/addons-vauxoo pull request #1559
Opened 2022-08-23 21:58 UTC by agarzaarvizu

## This PR refers to the task[#53862](https://www.vauxoo.com/web#action=1928&cids=1&id=53862&menu_id=1490&model=project.task&view_type=form)

- add pre-migration in order to remove inherited views of_product_template_tann_inhrt view

2022-08-23 21:58 UTC, agarzaarvizu commented
@luisg123v Please review.

2022-08-23 22:04 UTC, luisg123v requested changes
Fix title:
- Not an ADD but a FIX, we're fixing an issue
- Please be more descriptive in titles, I can't know what's being fixed here. Title should say what's being fixed, in the description you can mention the how, which is a migration script

2022-08-23 22:04 UTC, luisg123v commented on product_cost_usd/migration/11.0.1.0.0/pre-migration.py
> +    if not version:
May be removed

2022-08-23 22:04 UTC, luisg123v commented on product_cost_usd/migration/11.0.1.0.0/pre-migration.py
> +def delete_inherited_views(cr):
Missing increasing version

2022-08-23 22:04 UTC, luisg123v commented
Hi @andreaarce,

Could you point your change to use this branch, please?

So we know if it's working.

2022-08-23 22:18 UTC, agarzaarvizu commented
@luisg123v Done

2022-08-23 23:55 UTC, luisg123v approved these changes
LGTM, just waiting for @andreaarce's approval.

FYI you had a typo in title, but since it was only in the PR, I fixed it.

2022-08-25 21:13 UTC, luisg123v requested changes
Version increase was lost during rebase.

2022-08-25 21:32 UTC, agarzaarvizu commented
@luisg123v Done

2022-08-25 21:39 UTC, luisg123v approved these changes

2022-08-25 21:39 UTC, merged