[MIG] accoun_move_report: Migrate account_move_report to 15.0 t#54296
Vauxoo/addons-vauxoo pull request #1565
Opened 2022-08-29 14:16 UTC by ajqn9094

2022-08-29 14:41 UTC, ajqn9094 commented
@luisg123v Could you review please?

Thanks in advance!

2022-08-29 16:10 UTC, luisg123v requested changes
Please keep commit history, you can follow instructions depicted [in the OCA](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch)

2022-08-29 16:57 UTC, ajqn9094 commented
> Please keep commit history, you can follow instructions depicted [in the OCA](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch)

On it, thanks!

2022-08-29 18:35 UTC, ajqn9094 commented
@luisg123v command applied to get the historical from account_move_report

2022-08-29 22:29 UTC, desdelinux approved these changes
LGTM @luisg123v @ajqn9094

2022-08-31 22:41 UTC, luisg123v requested changes
- Missing black commit from v14. Besides, already fixed issues are not fixed here yet. You should bring history again.
- Title: remove task ID
- Title: remove module name from short description (title) as it's redundant. It should be: `[MIG] module_name: migrate to 15.0`

2022-08-31 22:41 UTC, luisg123v commented on account_move_report/__manifest__.py
> +    "data": ["views/account_reports.xml", "views/account_move_report.xml"],
Trailing comma, this was already fixed in v14

2022-08-31 22:54 UTC, hugho-ad commented
why did you not promote use https://git.vauxoo.com/vauxoo/mexico/-/tree/15.0/l10n_mx_edi_account_move_report?

I think they are almost the same

2022-08-31 22:56 UTC, luisg123v commented
@desdelinux could you review @hugho-ad's proposal, please?

2022-09-01 00:05 UTC, desdelinux commented
> why did you not promote use https://git.vauxoo.com/vauxoo/mexico/-/tree/15.0/l10n_mx_edi_account_move_report?
> 
> I think they are almost the same



> [l10n_mx_edi_account_move_report](https://git.vauxoo.com/vauxoo/mexico/-/tree/15.0/l10n_mx_edi_account_move_report)?

l10n_mx_edi_account_move_report contains fields that only apply to Mexico.

In multi-country instances, this may not be expected.

cc @luistorresm @hbto could you review @hugho-ad proposal, please?

2022-09-01 00:13 UTC, desdelinux commented
@luistorresm Recommend that we at vauxoo use l10n_mx_edi_account_move_report for auditing.

So let's proceed that way.

@luisg123v What other client do you have mapped that use account_move_report?

cc @hugho-ad

2022-09-01 00:55 UTC, luisg123v commented
> @luisg123v What other client do you have mapped that use account_move_report?

None that I'm aware of

@ajqn9094, please replace `account_move_report` by `l10n_mx_edi_account_move_report` in v14 and let's forward-port the change to it to v15.

2022-09-01 00:55 UTC, closed without merging