[IMP] *: black lints
Vauxoo/addons-vauxoo pull request #1568
Opened 2022-08-30 01:52 UTC by ajqn9094

Black lints corrected on all modules

2022-08-30 02:13 UTC, ajqn9094 commented
@luisg123v Could you review please

Thanks in advance

2022-08-30 03:10 UTC, luisg123v requested changes
`[IMP] module_name: black, isort, prettier`

Keep that order and don't include task ID

2022-08-30 03:37 UTC, ajqn9094 commented
> `[IMP] module_name: black, isort, prettier`
> 
> Keep that order and don't include task ID

Done

2022-08-30 17:37 UTC, luisg123v requested changes

2022-08-30 17:37 UTC, luisg123v commented on account_analytic_business_unit/__manifest__.py
> +    "depends": ["account", 'analytic'],
- Double quotes
- Add trailing comman so a module per line si preserved

2022-08-30 17:37 UTC, luisg123v commented on stock_by_warehouse_mrp_bom/__manifest__.py
> +    "data": ["views/mrp_bom_line_views.xml", "views/mrp_bom_views.xml"],
Trailing comma

2022-08-30 18:22 UTC, ajqn9094 commented on account_analytic_business_unit/__manifest__.py
> +    "depends": ["account", 'analytic'],
Done

2022-08-30 18:22 UTC, ajqn9094 commented on stock_by_warehouse_mrp_bom/__manifest__.py
> +    "data": ["views/mrp_bom_line_views.xml", "views/mrp_bom_views.xml"],
Done

2022-08-30 18:29 UTC, ajqn9094 commented
@luisg123v Changes applied requested applied, additionally similar details found in the other commits are corrected.

2022-08-30 18:35 UTC, luisg123v requested changes

2022-08-30 18:35 UTC, luisg123v commented on default_warehouse_from_sale_team/models/crm_team.py
> +        help="In this field can be defined a default warehouse for " "the related users to the sales team.",
```suggestion
        help="In this field can be defined a default warehouse for the related users to the sales team.",
```

2022-08-30 19:05 UTC, ajqn9094 commented on default_warehouse_from_sale_team/models/crm_team.py
> +        help="In this field can be defined a default warehouse for " "the related users to the sales team.",
Done

2022-08-31 21:16 UTC, luisg123v approved these changes

2022-08-31 21:16 UTC, merged