[MIG] account_multicompany_code: Migrate to v15
Vauxoo/addons-vauxoo pull request #1575
Opened 2022-10-19 22:40 UTC by JesusValdez96

- Fix black, isort and prettier lints
- Fix pylints in res_company model (use Python 3 style super() without arguments)

2022-10-19 22:48 UTC, JesusValdez96 commented
@hugho-ad Please review this.

2022-10-20 00:52 UTC, luisg123v requested changes
We accorded by mail when this module was migrated to v14 that we will depend on the module `res_company_code`, because its constraint is more efficient (it's an SQL constraint instead of a Python one) and the code is considered also on the company switcher. That module is [here](https://github.com/OCA/multi-company/tree/14.0/res_company_code)

2022-10-20 03:37 UTC, hugho-ad commented
@luisg123v 

why not to use only the oca one?

the mig to v14 was performed by you
https://github.com/Vauxoo/addons-vauxoo/pull/1458

2022-10-20 04:02 UTC, hugho-ad commented
ya lei los hilos completos sobre este modulo 
 creo que @nhomar no espera esta dependencia del modulo de la oca.

En mi opinión deberiamos manterner nuestro modulo sin depender  de la oca

2022-10-20 14:49 UTC, luisg123v commented
No, what @nhomar said was to don't replace this module with the OCA's one, because this module also adds other feature.

This does two things:
1. Add a code to the company and ensure it's unique
2. Use that code in accounts

The 1st point is covered by the OCA module on a more complete and efficient manner, so I think it should be used, and only the 2nd point should be covered from our side

2022-10-20 22:01 UTC, hugho-ad approved these changes

2022-10-20 22:02 UTC, hugho-ad commented
Strategic merge

We will NOT depend on OCA module, this will remain as it's!

2022-10-20 22:02 UTC, merged

2022-10-31 23:26 UTC, luisg123v reviewed
Better late than never

2022-10-31 23:26 UTC, luisg123v commented on account_multicompany_code/__manifest__.py
> +        "views/company_view.xml",
`res_company_views.xml`

FYI (for next migration) black-related changes goes into a separated commit, to be able to distinguish formatting changes from actual migration changes

2022-10-31 23:26 UTC, luisg123v commented on account_multicompany_code/models/account.py
> +class AccountJournal(models.Model):
Move to its own file, each model should be placed on a separated file

2022-10-31 23:26 UTC, luisg123v commented on account_multicompany_code/models/res_company.py
> +    def unique_code(self):
Move to SQL constraint, for efficiency, as the module `res_company_code` does

2022-10-31 23:26 UTC, luisg123v commented on account_multicompany_code/tests/test_multicompany_code.py
> +    def setUp(self):
`setUpClass`

2022-10-31 23:26 UTC, luisg123v commented on account_multicompany_code/views/company_view.xml
> +                <field name="code" required="1" />
Missing changes on other views, check module `res_company_code` for more context

2022-10-31 23:28 UTC, luisg123v commented
@LuisMzz could you take care of the review I left post migration, please?

2022-10-31 23:33 UTC, luisg123v commented
@hugho-ad prefer merging using the rebase method, to don't create a merge commit.