[ADD] stock_manual_transfer: New module added T#57669
Vauxoo/addons-vauxoo pull request #1581
Opened 2022-12-13 23:43 UTC by agarzaarvizu

- New module added in order to allow the user to create stock transfers manually.

2022-12-16 06:17 UTC, agarzaarvizu commented
@luisg123v Done, please review

2022-12-16 21:15 UTC, luisg123v requested changes
Missing translations

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/demo/stock_demo.xml
> +        <field name="name">Demo Route</field>
More specific, please, it should be self-explanatory.

Previous names were OK

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/crm_team.py
> +    default_warehouse_id = fields.Many2one("stock.warehouse", company_dependent=True)
Remove

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +    _inherit = ["mail.thread"]
Missing activity mixin

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +    _description = "Stock Manual Transfer"
Remove "Stock"

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +        route = self.env["stock.location.route"].browse(self.route_id.id)
No need to browse, you already have it handy

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +        if route.rule_ids.warehouse_id != self.warehouse_id:
```suggestion
        if self.warehouse_id not in route.rule_ids.warehouse_id:
```

Because a route can have rules from different warehouses

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +                _("The warehouse selected does not match the warehouse assigned to the rule in the route")
The selected route doesn't have configured rules on the selected warehouse.

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer.py
> +            record.picking_ids = record.procurement_group_id.picking_ids
I think it may be related

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/models/stock_manual_transfer_line.py
> +    product_uom_qty = fields.Float("Quantity", required=True, default=1.0)
Numeric fields can't be required, as 0 is a valid value

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/security/ir.model.access.csv
> +access_stock_can_stock_manual_transfer,stock_can_stock_manual_transfer,model_stock_manual_transfer,group_stock_manual_transfer,1,1,1,1
Be aware you will need a migration script on tanner-common for this group

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/security/res_groups.xml
> +        <field name="name">Stock Manual Transfer Group</field>
Remove "group", this is a group.

Maybe

"Can make manual transfers"

And remove help

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +    def setUp(self):
setUpClass

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +            with tr.transfer_line_ids.new() as line:
both with's may be joined

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +        self.env.user.groups_id |= self.manual_transfer_group
The group should have the admin and root users by default

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +                    # Warehouse set on sales team
Remove, this is not applicable here

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +        draft_transfer.unlink()
Implement a new test to cover the new validation you added

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/__manifest__.py
> +    "category": "Stock",
"Inventory/Inventory"

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/__manifest__.py
> +        "sale_stock",
Only stock is required

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/README.rst
> +and create a stock move:
Transfer (picking)

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/README.rst
> +Functional Rationale:
Here goes the module name

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/README.rst
> +It allows you to make a stock transfer manually using a custom route.
This module allows you to trigger transfers using a specific route, as it were triggered by a reordering rule.

2022-12-16 21:15 UTC, luisg123v commented on stock_manual_transfer/__manifest__.py
> +    "website": "https://www.vauxoo.com",
Missing summary

2022-12-20 22:21 UTC, agarzaarvizu commented
@luisg123v Done, please review

2022-12-22 21:24 UTC, luisg123v commented on stock_manual_transfer/__manifest__.py
> +        "sale_stock",
You didn't remove mail

2022-12-22 21:47 UTC, luisg123v requested changes

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr ""
Missing translation

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Puede hacer transferencia manual"
Plural

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Click para agregar una nueva transferencia manual"
Missing trailing dot

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Hacer transferencia"
- Realizar
- Plural

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Linea de transferencia manual"
l**í**nea

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr ""
Missing translation

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Categoria de unidades de medida del producto"
- Singular
- Missing acute accents

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Recepción de ruta"
Ruta de recepción

But in English is wrong.

Just name it reception, because "route" is redundant, as they are all routes

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Sequencia"
```suggestion
msgstr "Secuencia"
```

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Lineas de transferencia"
l**í**neas

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr ""
missing

2022-12-22 21:47 UTC, luisg123v commented on stock_manual_transfer/tests/test_stock_manual_transfer.py
> +        self.warehouse_route_reception.rule_ids.warehouse_id -= self.warehouse
```suggestion
        self.warehouse_route_reception.rule_ids.warehouse_id = False
```

2022-12-22 22:00 UTC, luisg123v requested changes
Remove logo, this is not a customer

2022-12-23 07:56 UTC, agarzaarvizu commented
@luisg123v Done

2022-12-23 19:36 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Recepción de ruta"
Not fully applied, not renamed in English

2022-12-23 19:37 UTC, luisg123v commented on stock_manual_transfer/i18n/es.po
> +msgstr "Hacer transferencia"
This same issue is in the group translation

2022-12-25 23:51 UTC, agarzaarvizu commented
@luisg123v Done

2022-12-26 00:05 UTC, luisg123v approved these changes
LGTM :+1:

2022-12-26 00:05 UTC, merged