[FIX] default_warehouse_from_sale_team: pre-commit-vauxoo error
Vauxoo/addons-vauxoo pull request #1587
Opened 2023-01-23 21:12 UTC by montesinose

Fix lint: - (implicit-str-concat)

2023-01-23 21:58 UTC, montesinose commented
Please review @luisg123v

2023-01-23 22:04 UTC, luisg123v requested changes
Commit description: I think there's a missing new line after colon, is it intentional?

2023-01-23 22:04 UTC, luisg123v commented on search_action_domain/README.rst
> +section. In other words, the user might use complex queries to search the records.
Apply this in a separated commit, as it's a different module. This same PR so we can see it's green

2023-01-23 23:12 UTC, montesinose commented
> Commit description: I think there's a missing new line after colon, is it intentional?

It is. Do you want me to change it?

2023-01-23 23:20 UTC, luisg123v commented
No, if it looks good to you, then I won't object.

2023-01-24 00:17 UTC, luisg123v approved these changes

2023-01-24 00:17 UTC, merged