[MIG] Initialice branch for v16
Vauxoo/addons-vauxoo pull request #1588
Opened 2023-02-13 22:41 UTC by isaako34

- CI files are initialized (variables.sh, gitignore, README.md, CONTRIBUTING.md, .travis.yml)

- Modules have not been migrated yet.

2023-02-14 01:02 UTC, isaako34 commented
Hello @hugho-ad could you review it, please.

2023-02-14 22:14 UTC, hugho-ad commented on .travis.yml
> +  - travis_after_tests_success
EOF

2023-02-14 22:14 UTC, hugho-ad commented on variables.sh
> +export PSQL_VERSION="11"
i think you can use 13.0

2023-02-14 22:18 UTC, luisg123v requested changes
I think we need to close this PR, I first need to apply changes in v15 to use VXCI instead of MQT.

2023-04-15 00:24 UTC, luisg123v commented
Superseded by #1600

2023-04-15 00:24 UTC, closed without merging