[REF] pr_line_related_po_line: Clean module for migration to v16
Vauxoo/addons-vauxoo pull request #1591
Opened 2023-02-17 15:26 UTC by VEscaname

- Changed license to OPL-1 in manifest
- In purchase_order_views model attribute was set after id
- In the same view encoding was added to the header

2023-02-17 17:58 UTC, VEscaname commented
@luisg123v could you check this PR please?

2023-02-20 19:55 UTC, luisg123v requested changes

2023-02-20 19:55 UTC, luisg123v commented on pr_line_related_po_line/static/description/index.html
> +    overwrites the method to create a purchase order line to ad the id of a purchase requistition line to that
```suggestion
    overwrites the method to create a purchase order line to ad the id of a purchase requisition line to that
```

But this part gets technical, someone without technical knowledge won't know what's a method.

I'd say something like "it also adds a new field to purchase order lines to link them to the created requisition lines.

2023-02-20 19:55 UTC, luisg123v commented on pr_line_related_po_line/__manifest__.py
> +    "license": "OPL-1",
License is correct in this case, because modules in public repos like this one or the OCA are expected to be free software

2023-02-20 19:55 UTC, luisg123v commented on pr_line_related_po_line/models/purchase_order_line.py
Remove extra blank line.

2023-02-20 19:55 UTC, luisg123v commented on pr_line_related_po_line/views/purchase_order_views.xml
> +<?xml version="1.0" encoding="utf-8" ?>
Uppercase UTF

2023-02-23 16:18 UTC, VEscaname commented
@luisg123v Could you please check this again?

2023-02-24 21:15 UTC, luisg123v requested changes

2023-02-24 21:15 UTC, luisg123v commented on pr_line_related_po_line/views/purchase_order_views.xml
> +<<<<<<< HEAD
Conflicts were not solved correctly

2023-02-27 16:53 UTC, VEscaname commented
@luisg123v That last change should be correctly applied now. Could you review please?

2023-02-27 18:52 UTC, luisg123v requested changes
- In title, don't mention migration. This is a module shared by other projects, for which migration wouldn't make sense/apply. Just say general cleanup
- Update PR description to remove license change

2023-02-28 01:28 UTC, luisg123v commented
@VEscaname,

New task for this: 66089.

I'll move your current timesheet to that one.

2023-03-01 14:18 UTC, VEscaname commented
@luisg123v title and PR description should be fixed now. Could you check this again?

2023-03-01 15:12 UTC, luisg123v commented
@VEscaname you forgot to update commit's title

2023-03-01 22:20 UTC, VEscaname commented
@luisg123v just fixed the commit title as well

2023-03-01 22:36 UTC, luisg123v approved these changes

2023-03-01 22:37 UTC, merged