[MIG] account_chatter: Migration to 16.0 T#66175
Vauxoo/addons-vauxoo pull request #1592
Opened 2023-02-23 16:33 UTC by VEscaname

2023-02-24 00:29 UTC, VEscaname commented
@luisg123v could you review this please?

2023-02-24 21:34 UTC, luisg123v requested changes

2023-02-24 21:34 UTC, luisg123v commented on account_chatter/__manifest__.py
> -# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).
Apply this change in v15.

BTW, I noticed they were not removed from file `models/__init__.py`, along with all non-migration changes.

2023-02-24 21:34 UTC, luisg123v commented on account_chatter/models/account_account.py
> -
Apply change in previous version

2023-02-24 21:34 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +     <record id="view_account_form_show_chatter" model="ir.ui.view">
Wrong indentation

2023-02-24 21:34 UTC, luisg123v commented on account_chatter/views/account_move_views.xml
> -        <field name="groups_id" eval="[(4, ref('account_chatter.group_show_account_chatter_notifications'))]" />
Are you sure this doesn't work anymore?

Is ee the field [still exists in v16](https://github.com/odoo/odoo/blob/79dc6384329b1e8bd2338160d62028ac0c1cdce4/odoo/addons/base/models/ir_ui_view.py#L263), so it should be possible

2023-02-24 21:34 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +                <t groups="account_chatter.group_show_account_chatter_notifications">
Does this work?

Take into account t directives only work in QWeb templates, they dont in standard views like form or tree view.

How is this element rendered? You may check by accessing Developer tools -> Fields view get, which shows you the rendered XML.

2023-03-01 14:16 UTC, VEscaname commented
@luisg123v could you review the changes again please?

2023-03-01 18:13 UTC, luisg123v commented
@VEscaname missing new commits from 15.0

2023-03-01 18:16 UTC, luisg123v requested changes

2023-03-01 18:16 UTC, luisg123v commented on account_chatter/views/account_account_views.xml
> +    <record id="view_account_form_show_chatter" model="ir.ui.view">
Since this is now a standard inheritance (without groups), ID should match inherited view

2023-03-02 16:48 UTC, VEscaname commented
@luisg123v could you review once again?

2023-03-03 01:23 UTC, luisg123v approved these changes
LGTM :+1: 

I'll merge after CI is initialized

CC @desdelinux

2023-03-03 23:28 UTC, merged