[REF] default_warehouse_from_sale_team: follow guidelines to clean the code T#63809
Vauxoo/addons-vauxoo pull request #1598
Opened 2023-03-03 18:48 UTC by rolandojduartem

2023-03-03 18:49 UTC, rolandojduartem commented
Hi, @luisg123v, please, could you review this PR?

cc @desdelinux

2023-03-04 00:17 UTC, luisg123v requested changes

2023-03-04 00:17 UTC, luisg123v commented on default_warehouse_from_sale_team/demo/crm_team_demo.xml
> +    <record id="stock_warehouse_default_team" model="stock.warehouse">
It seems records are duplicated across files

2023-03-04 00:17 UTC, luisg123v commented on default_warehouse_from_sale_team/security/ir_rule_security.xml
> +            eval="[(6, 0, [ref('default_warehouse_from_sale_team.group_manager_default_warehouse_spt')])]"
- command syntax (separated commit)
- Superfluous module in external ID (look for other possible cases)

2023-03-04 00:17 UTC, luisg123v commented on default_warehouse_from_sale_team/security/ir_rule_security.xml
> +<odoo noupdate="0">
Superfluous noupdate 0 (separated commit).

Same in similar cases

2023-03-07 16:26 UTC, rolandojduartem commented
Hi, @luisg123v, could you review this PR? The red CI is not related to these changes.

2023-03-07 21:27 UTC, luisg123v approved these changes

2023-03-07 21:28 UTC, merged