[IMP] stock_by_warehouse: Add tests to verify the warehouses_stock_recompute functionality T#63809
Vauxoo/addons-vauxoo pull request #1610
Opened 2023-04-05 00:41 UTC by rolandojduartem

2023-04-05 01:00 UTC, rolandojduartem commented
Hi, @luisg123v, please, could you review this PR?

cc @desdelinux

2023-04-05 15:34 UTC, luisg123v requested changes

2023-04-05 15:34 UTC, luisg123v commented on stock_by_warehouse/tests/test_stock_available_unreserved.py
> +        self.env.user.groups_id = [Command.link(self.env.ref("stock.group_stock_multi_warehouses").id)]
Use `|=`, it's simpler

2023-04-05 15:34 UTC, luisg123v commented on stock_by_warehouse/tests/test_stock_available_unreserved.py
>  class TestStockLogisticsWarehouse(TransactionCase):
setUpClass

2023-04-05 20:54 UTC, rolandojduartem commented
Hi, @luisg123v, ready!

2023-04-06 15:29 UTC, luisg123v approved these changes

2023-04-06 15:29 UTC, merged