[IMP] stock_by_warehouse_purchase: Add tests to verify the warehouses_stock_recompute functionality T#63809
Vauxoo/addons-vauxoo pull request #1611
Opened 2023-04-05 01:37 UTC by rolandojduartem

2023-04-05 01:46 UTC, rolandojduartem commented
Hi, @luisg123v, please, could you review this PR?

cc @desdelinux

2023-04-05 15:39 UTC, luisg123v requested changes

2023-04-05 15:39 UTC, luisg123v commented on stock_by_warehouse_purchase/tests/test_purchase_order_line.py
> +        cls.env.user.groups_id = [Command.link(cls.env.ref("stock.group_stock_multi_warehouses").id)]
`|=`

2023-04-05 20:53 UTC, rolandojduartem commented
Hi, @luisg123v, ready!

2023-04-06 15:57 UTC, luisg123v approved these changes

2023-04-06 16:08 UTC, merged