[IMP] default_warehouse_from_sale_team: Add sale_team_ids to the invalidation fields T#63809
Vauxoo/addons-vauxoo pull request #1612
Opened 2023-04-18 16:26 UTC by rolandojduartem

2023-04-18 16:36 UTC, luisg123v requested changes

2023-04-18 16:36 UTC, luisg123v commented on default_warehouse_from_sale_team/models/res_users.py
> +        invalidated_fields = super()._get_invalidation_fields()
```suggestion
        invalidation_fields = super()._get_invalidation_fields()
```

2023-04-18 17:07 UTC, rolandojduartem commented on default_warehouse_from_sale_team/models/res_users.py
> +        invalidated_fields = super()._get_invalidation_fields()
Done!

2023-04-18 17:07 UTC, rolandojduartem commented
@luisg123v, please, could you review this PR?

cc @desdelinux

2023-04-20 23:08 UTC, luisg123v approved these changes

2023-04-20 23:09 UTC, merged