[MIG] internal_transfer_with_agreed_amount: Migration to 17.0
Vauxoo/addons-vauxoo pull request #1670
Opened 2024-06-13 20:42 UTC by CLaurelB

Changelog:
- Replace `attrs` with an expression for the `invisible` attribute in the view.
- Add payment amount and currency update after the move is set to draft. This is because the undoing of the reconciliation triggers an update on the payment, and the amount gets updated to the previous agreed amount along with its corresponding currency. This happens when the agreed amount is edited.
- Fix ambiguous variable name.

2024-06-13 22:49 UTC, CLaurelB commented
@randall-vx @luisg123v could you review, please?

2024-06-17 19:00 UTC, luisg123v requested changes

2024-06-17 19:00 UTC, luisg123v commented on internal_transfer_with_agreed_amount/views/account_payment_views.xml
> +                    invisible="is_internal_transfer == False or state != 'draft'"
`not is_internal_transfer`

Same below.

2024-06-17 19:00 UTC, luisg123v commented on internal_transfer_with_agreed_amount/tests/test_internal_transfer_with_agreed_amount.py
> +        eur_aml = aml.full_reconcile_id.reconciled_line_ids.filtered(lambda line: line != aml)
This commit goes in the previous version.

2024-06-17 19:00 UTC, luisg123v commented on internal_transfer_with_agreed_amount/i18n/es.po
> +"Project-Id-Version: Odoo Server 16.0+e\n"
Missing updating translations. At the OCA this step is not required because they handle translations on a separate place (Weblate), but we don't.

2024-06-18 15:52 UTC, CLaurelB commented on internal_transfer_with_agreed_amount/tests/test_internal_transfer_with_agreed_amount.py
> +        eur_aml = aml.full_reconcile_id.reconciled_line_ids.filtered(lambda line: line != aml)
Moved to the previous version in the following PR: https://github.com/Vauxoo/addons-vauxoo/pull/1671

2024-06-18 18:39 UTC, luisg123v approved these changes
LGTM :+1:

2024-06-18 18:40 UTC, merged