[IMP] default_warehouse_from_sale_team: hook to fill allowed salesteams T#79454
Vauxoo/addons-vauxoo pull request #1673
Opened 2024-07-06 03:40 UTC by luisg123v

Implement a hook to f.ill allowed salesteams in users that are already members of any team

Since this module implements a feature to restrict what sales teams a user may be member of, users that already belong to any team are

configured to be allowed for those teams, to avoid inconcistencies between allowed and already-configured memberships. In other words, if I already belong to a team, it means I should be allowed to belong to it.

2024-07-06 04:00 UTC, xmglord requested changes

2024-07-06 04:00 UTC, xmglord commented on default_warehouse_from_sale_team/hooks.py
> +    """Fill allowed salesteams in users that are already members of any team
missing dot at the end of line

2024-07-06 04:00 UTC, xmglord commented on default_warehouse_from_sale_team/hooks.py
> +    Since this module implements a feature to restrict what sales teams a user may be member of, users that already
what sales teams -> **which** sales teams
a user may be member of -> a user may be **a** member of
inconcistencies -> incon**s**istencies

2024-07-06 04:02 UTC, xmglord commented
commit description:
f.ill -> fill
missing final dot at the first paragraph
same comments as in docstring

2024-07-06 04:09 UTC, luisg123v commented on default_warehouse_from_sale_team/hooks.py
> +    """Fill allowed salesteams in users that are already members of any team
TL;DR
My understanding was 1st line of a multi-line docstring shouldn't include a trailing dot, similar as commit titles. However, by reading [the docstring conventions for multi-line comments](https://peps.python.org/pep-0257/#multi-line-docstrings), I see, while not explicitly mentioned, the provided example includes it. For this, I've changed it.

Short answer: applied, thanks!

2024-07-06 04:36 UTC, luisg123v commented
@xmglord Fixes to commit messages applied.

2024-07-06 05:01 UTC, xmglord commented on default_warehouse_from_sale_team/hooks.py
> +    """Fill allowed salesteams in users that are already members of any team
Thanks to you for the docstring conventions link.

2024-07-06 05:03 UTC, xmglord commented
> @xmglord Fixes to commit messages applied.

Not applied yet

2024-07-06 17:58 UTC, luisg123v commented on default_warehouse_from_sale_team/hooks.py
> +    Since this module implements a feature to restrict what sales teams a user may be member of, users that already
Sorry, I didn't see this comment, applied. I modified the whole message for clarity.

BTW, I don't think replacing "what" by "which" is necessary on this case, but applied anyway.

2024-07-06 23:18 UTC, xmglord approved these changes
LGTM :+1:

2024-07-06 23:19 UTC, xmglord commented on default_warehouse_from_sale_team/hooks.py
> +    Since this module implements a feature to restrict what sales teams a user may be member of, users that already
Since is not necessary lets say it was a nitpick

2024-07-08 15:36 UTC, TeposteAJ commented
LGTM :+1:

2024-07-08 15:37 UTC, TeposteAJ approved these changes
LGTM 👍

2024-07-08 17:41 UTC, desdelinux approved these changes

2024-07-08 17:42 UTC, merged